### ISSUE TITLE
Design system / BV Go user experience improvements

### ISSUE THREAD

**Issue by bstiawan** [Bukit-Vista/roadmap#60]
## Goal: 
- Triggering more interaction instead of expecting users to go to the page they want to see

## Structure: 
- Messages, instead of separate page between notifications and messages, we combine them as messages page. The message could be:
  - About guests (message, payout, updates, check in, etc)
  - About property (newsletter, league updates, non guest related notifications)
  - Support message (upcoming feature)
Each of those message will still link to the relevant page. 
![Image](https://github.com/user-attachments/assets/68558515-cc21-4842-875f-9d15657cfc79)

## Performance:
- Delayed real-time
  - Any data that have been fetched from the server is stored locally, when user opens it, the old data will be used first. This will remove any loading process.
  - Once the page opens, new data will be fetched in the background with small indicator. When new data arrives, the page will be updated (without refreshing the entire page). Reference app with similar approach: Slack, Coda, Twitter.
  - Apply this method for page: Dashboard, bookings, my property, messages, profile.

## Readability
- Typeface
  - We are changing to a more readable typeface with thinner line but clean spacing
- Icons
  - Custom icons for brand consistency
  - ![Image](https://github.com/user-attachments/assets/7816a6a2-6c28-48e3-af2b-b43ee1c8c00c)
- Spacing
  - Fixing size, empty space, and borders
- Colors
  - Refining better use of colors to emphasize simplicity and better visibility on important points

**Comment by bstiawan** [comment]
Projects:

- [ ] Design system
- [ ] Quick load and delayed refresh
- [ ] Messages page

**Comment by bstiawan** [comment]
## Development principles

- We will create a reusable UI component, starting from the simplest ones, as a variable that can be set and affect all components
  - typeface
  - size
  - space (padding, margin, gutter)
  - elevation
- This should be implemented in alignment with the design provided in Figma
  - When we want to make changes to the UI, we only need to change the variable

**Comment by krisnaBukitVista** [comment]
# Project Plan: User Interface and Performance Improvement 

## Description
This project focuses on addressing key performance and readability issues in the platform by optimizing real-time data loading and enhancing the UI design. The primary goal is to improve user experience through faster data access, seamless updates, and a more readable, visually appealing interface. The scope includes applying real-time optimizations and design updates across critical user pages: Dashboard, Bookings, My Property, Messages, and Profile.

##  Problem
- Performance Issue: Delayed Real-Time Data Users experience delays when accessing real-time data. Currently, fetching new data involves noticeable loading times, causing frustration for users who expect instant access to updated information.
- Readability Issue The platform's readability is affected by the choice of typeface, iconography, spacing, and colors. Users may find it challenging to navigate the interface, leading to inefficient workflows and a lack of brand consistency.

## Solution
- Performance Optimization
  - Local Data Storage: Cache previously fetched data locally so that when a user revisits the page, the older data is instantly available, reducing any loading time.
  - Background Data Fetching: While the user views the page, updated data is fetched in the background with a small visual indicator, ensuring that the page automatically refreshes without needing a full reload. This method is inspired by apps like Slack, Coda, and Twitter.

- UI/UX Readability Enhancements
  - Typeface Update: Replace the current typeface with a more readable one that features thinner lines but retains clean spacing.
  - Custom Icons: Design custom icons to enhance brand consistency.
  - Spacing Adjustments: Refine empty spaces, borders, and sizing for a more balanced layout.
  - Color Refinement: Apply a simpler color scheme that highlights important content while maintaining visual clarity.

## Measurement metrics 
- page load time reduction: decreased in perceived load times when switching between pages
- readability feedback: Collect qualitative feedback on the new UI

## SLA 
- page load reduction: decreased in perceived load times with 50% decrease
- Readability Feedback: Collect qualitative feedback on the new UI, with a target of 85% positive responses on readability improvements.

**Comment by katibpasha** [comment]
# Final Evaluation

### Property Owner's side
- All main pages (dashboard, booking, my property, inbox, and menu) have implemented new design system
- section today di dashboard, inbox, and menu belum implement font baru
- Navigation icons have updated and aligned with the new design guideline
- My property page's performance has been enhanced by API chunking

### Staff's side
- All main pages (dashboard, booking, my property, inbox, and menu) have implemented new design system
- section today di dashboard, inbox, and menu belum implement font baru
- Navigation icons have updated and aligned with the new design guideline
- My property page's performance has been enhanced by API chunking

## Finding
- When opening newsletter details from notifications, the back button doesn't work.

**Comment by Vidiskiu** [comment]
Overall Point: 5
Functional Complexity: 0.5

> The changes requested are mostly UI/UX based, with minimal changes to functional complexity as they mainly involve altering how information is presented rather than significant changes to business logic.

Technical Complexity: 1.5

> While there are not many architectural changes, the issue outlines a need for local storage of data and background updates which introduces moderate technical complexity due to the requirement for efficient data management and possibly some changes to the existing data flow.

UI/UX Complexity and Impact: 1.25

> A substantial UI/UX overhaul is indicated, including changes to interaction design, typeface, icon design, spacing, and color usage which will have a significant impact on the overall user experience.

Testing and Quality Assurance: 1.25

> The UI/UX changes will require thorough testing to ensure consistency across different screens and conditions. The real-time data feature mentioned will require cross-platform and performance testing to validate the new approach.

Risk and Dependencies: 0.5

> Some risks are involved in ensuring UI consistency and performance, but the issue does not mention external dependencies or significant uncertainties.
